version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app
      - /app/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app  
      - /app/node_modules